import './globals.css'

export const metadata = {
  title: "Prayer Times",
  description: "Generated By Fikry",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
